'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const scripts = manifest.content_scripts[0].js;
for (const platform of ['facebook', 'instagram', 'twitter', 'tiktok']) {
  assert.ok(scripts.includes(`scrapers/${platform}.js`), `${platform} scraper must be a separate content module`);
}
assert.ok(scripts.includes('scrapers/oxu.js'), 'oxu.az scraper must be a separate content module');
assert.ok(scripts.includes('scrapers/media.js'), 'media.az scraper must be a separate content module');
assert.ok(scripts.includes('scrapers/one-news.js'), '1news.az scraper must be a separate content module');
assert.ok(scripts.includes('scrapers/haqqin.js'), 'haqqin.az scraper must be a separate content module');
assert.ok(scripts.includes('scrapers/caliber.js'), 'caliber.az scraper must be a separate content module');
assert.ok(scripts.includes('scrapers/qafqazinfo.js'), 'qafqazinfo.az scraper must be a separate content module');
assert.equal(scripts.at(-1), 'content.js');
assert.ok(manifest.host_permissions.includes('*://oxu.az/*'), 'oxu.az host permission is required');
assert.ok(manifest.content_scripts[0].matches.includes('*://oxu.az/*'), 'oxu.az content script match is required');
assert.ok(manifest.host_permissions.includes('*://media.az/*'), 'media.az host permission is required');
assert.ok(manifest.content_scripts[0].matches.includes('*://media.az/*'), 'media.az content script match is required');
assert.ok(manifest.host_permissions.includes('*://1news.az/*'), '1news.az host permission is required');
assert.ok(manifest.content_scripts[0].matches.includes('*://1news.az/*'), '1news.az content script match is required');
assert.ok(manifest.host_permissions.includes('*://haqqin.az/*'), 'haqqin.az host permission is required');
assert.ok(manifest.content_scripts[0].matches.includes('*://haqqin.az/*'), 'haqqin.az content script match is required');
assert.ok(manifest.host_permissions.includes('*://caliber.az/*'), 'caliber.az host permission is required');
assert.ok(manifest.content_scripts[0].matches.includes('*://caliber.az/*'), 'caliber.az content script match is required');
assert.ok(manifest.host_permissions.includes('*://qafqazinfo.az/*'), 'qafqazinfo.az host permission is required');
assert.ok(manifest.content_scripts[0].matches.includes('*://qafqazinfo.az/*'), 'qafqazinfo.az content script match is required');

const sourceFiles = [];
function walk(directory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (entry.name === '.git' || entry.name === 'node_modules' || entry.name === 'tests') continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) walk(fullPath);
    else if (/\.(js|html|json)$/.test(entry.name)) sourceFiles.push(fullPath);
  }
}
walk(root);
const sources = sourceFiles.map((file) => [file, fs.readFileSync(file, 'utf8')]);
const downloadCalls = sources.flatMap(([file, source]) => Array.from(source.matchAll(/chrome\.downloads\.download/g), () => file));
assert.deepEqual(downloadCalls.map((file) => path.relative(root, file)), ['core\\downloads.js']);

const directStateWrites = sources.flatMap(([file, source]) => source.includes('chrome.storage.local.set') ? [path.relative(root, file)] : []);
assert.deepEqual(directStateWrites, ['core\\storage.js']);

const joined = sources.map(([, source]) => source).join('\n');
for (const leakedToken of ['raulalishov', 'AlexeyMoro', 'Ds7B', '2v7$s4', 'pLYpMK']) assert.equal(joined.includes(leakedToken), false);
assert.equal(/DOMContentLoaded[^\n]+run|setTimeout\([^\n]+runStateMachine/.test(fs.readFileSync(path.join(root, 'content.js'), 'utf8')), false);
const instagramSource = fs.readFileSync(path.join(root, 'scrapers', 'instagram.js'), 'utf8');
assert.match(instagramSource, /Instagram uses direct search URL strategy/);
assert.match(instagramSource, /https:\/\/www\.instagram\.com\/explore\/search\/keyword\/\?q=/);
assert.match(instagramSource, /window\.location\.assign\(searchUrl\)/);
assert.doesNotMatch(instagramSource, /ctx\.navigation\.search\(/);
assert.doesNotMatch(instagramSource, /searchInput\(|openSearch\(|clickExactSuggestion\(/);
assert.match(instagramSource, /collectCarouselMedia/);
assert.match(instagramSource, /source\[src\]/);
assert.match(instagramSource, /Instagram carousel slide changed/);
const twitterSource = fs.readFileSync(path.join(root, 'scrapers', 'twitter.js'), 'utf8');
assert.match(twitterSource, /Date limit enabled; opening Advanced Search/);
assert.match(twitterSource, /Advanced search link found/);
assert.match(twitterSource, /input\[name="allOfTheseWords"\]/);
assert.match(twitterSource, /From date selected: \$\{dateLimit\.iso\}/);
assert.match(twitterSource, /Advanced search UI failed; using since: fallback URL/);
assert.match(twitterSource, /since:\$\{parsed\.iso\}/);
assert.match(twitterSource, /encodeURIComponent\(q\)/);
const oxuSource = fs.readFileSync(path.join(root, 'scrapers', 'oxu.js'), 'utf8');
assert.match(oxuSource, /source: 'oxu\.az'/);
assert.match(oxuSource, /\.custom-navbar-search-toggle/);
assert.match(oxuSource, /input\[name="query"\]/);
assert.match(oxuSource, /\.rt-news-item/);
assert.match(oxuSource, /news:openArticleTab/);
assert.match(oxuSource, /post-detail-content-inner\.resize-area > p/);
assert.match(oxuSource, /audio-block\[data-url\]/);
assert.match(oxuSource, /app\.parsers\.oxuDate/);
assert.doesNotMatch(oxuSource, /category:/);
assert.doesNotMatch(oxuSource, /post-item-category|breadcrumb-item\.active/);
const mediaSource = fs.readFileSync(path.join(root, 'scrapers', 'media.js'), 'utf8');
assert.match(mediaSource, /source: 'media\.az'/);
assert.match(mediaSource, /header__search-open/);
assert.match(mediaSource, /input\.header__search__input\[name="query"\]/);
assert.match(mediaSource, /\.post-block/);
assert.match(mediaSource, /news:openArticleTab/);
assert.match(mediaSource, /news-inner__desc p/);
assert.match(mediaSource, /news-inner__image img/);
assert.match(mediaSource, /video\[src\], source\[src\], audio\[src\]/);
assert.match(mediaSource, /app\.parsers\.mediaAzDate/);
assert.match(mediaSource, /input\[name="date_start"\], #start_date/);
assert.match(mediaSource, /Setting date_start input/);
assert.match(mediaSource, /Search submitted with date_start/);
assert.match(mediaSource, /Using fallback URL with date_start/);
assert.match(mediaSource, /date_start=\$\{parsed\.iso\}&date_end=&category=&sort_type=0/);
assert.match(mediaSource, /app\.parsers\.mediaAzDateLimit/);
assert.match(mediaSource, /app\.parsers\.mediaAzSearchUrl/);
assert.doesNotMatch(mediaSource, /category:/);
const oneNewsSource = fs.readFileSync(path.join(root, 'scrapers', 'one-news.js'), 'utf8');
assert.match(oneNewsSource, /source: '1news\.az'/);
assert.match(oneNewsSource, /#searchInput, input\[name="q"\], \.search form input/);
assert.match(oneNewsSource, /gsc-option-menu-container/);
assert.match(oneNewsSource, /Sorting results by Date/);
assert.match(oneNewsSource, /gsc-cursor-page/);
assert.match(oneNewsSource, /gsc-webResult\.gsc-result, \.gsc-result/);
assert.match(oneNewsSource, /news:openArticleTab/);
assert.match(oneNewsSource, /mainArticle \.content > p/);
assert.match(oneNewsSource, /authorNDate \.date/);
assert.match(oneNewsSource, /app\.parsers\.parse1NewsDate/);
assert.doesNotMatch(oneNewsSource, /category:/);
const haqqinSource = fs.readFileSync(path.join(root, 'scrapers', 'haqqin.js'), 'utf8');
assert.match(haqqinSource, /source: 'haqqin\.az'/);
assert.match(haqqinSource, /\.page-header__open-search-form-button/);
assert.match(haqqinSource, /form\.page-header__search-form input\[name="q"\], \.search-form__input\[name="q"\]/);
assert.match(haqqinSource, /search\/\$\{encodeURIComponent/);
assert.match(haqqinSource, /a\.news-list__item\.news-item, \.news-list__item\.news-item/);
assert.match(haqqinSource, /load-more__button/);
assert.match(haqqinSource, /news:openArticleTab/);
assert.match(haqqinSource, /article__content \.block-text p/);
assert.match(haqqinSource, /article__date/);
assert.match(haqqinSource, /block-photo img/);
assert.match(haqqinSource, /app\.parsers\.parseHaqqinDate/);
assert.doesNotMatch(haqqinSource, /category:/);
const caliberSource = fs.readFileSync(path.join(root, 'scrapers', 'caliber.js'), 'utf8');
assert.match(caliberSource, /source: 'caliber\.az'/);
assert.match(caliberSource, /\.header_button\.search_button, \.search_button/);
assert.match(caliberSource, /\.input_block input\[type="text"\]/);
assert.match(caliberSource, /search\/\$\{encodeURIComponent/);
assert.match(caliberSource, /\.float_block/);
assert.match(caliberSource, /float_block_title/);
assert.match(caliberSource, /float_block_time/);
assert.match(caliberSource, /backgroundImageUrl/);
assert.match(caliberSource, /Scrolling for more results/);
assert.match(caliberSource, /news:openArticleTab/);
assert.match(caliberSource, /\.post_body p/);
assert.match(caliberSource, /\.post_time/);
assert.match(caliberSource, /\.post_cover/);
assert.match(caliberSource, /app\.parsers\.parseCaliberDate/);
assert.doesNotMatch(caliberSource, /category:/);
assert.doesNotMatch(caliberSource, /views:/);
const qafqazinfoSource = fs.readFileSync(path.join(root, 'scrapers', 'qafqazinfo.js'), 'utf8');
assert.match(qafqazinfoSource, /source: 'qafqazinfo\.az'/);
assert.match(qafqazinfoSource, /#frmSearch input\[name="keyword"\]/);
assert.match(qafqazinfoSource, /news\/search\?keyword=\$\{encodeURIComponent/);
assert.match(qafqazinfoSource, /a\[href\*="\/news\/detail\/"\]/);
assert.match(qafqazinfoSource, /h4\.hemcinin, \.hemcinin/);
assert.match(qafqazinfoSource, /unsafeSearchArea/);
assert.match(qafqazinfoSource, /\.row\.toplinks/);
assert.match(qafqazinfoSource, /searchResultContainers/);
assert.match(qafqazinfoSource, /Search results container found/);
assert.match(qafqazinfoSource, /Header news skipped/);
assert.match(qafqazinfoSource, /Ignored header article/);
assert.match(qafqazinfoSource, /Search result accepted/);
assert.match(qafqazinfoSource, /\.yiiPager li\.next a\[href\]/);
assert.doesNotMatch(qafqazinfoSource, /\.yiiPager li\.page a\[href\]/);
assert.match(qafqazinfoSource, /visitedPageUrls/);
assert.match(qafqazinfoSource, /Next page URL/);
assert.match(qafqazinfoSource, /Navigating to next page/);
assert.match(qafqazinfoSource, /Waiting for page load \(timeout 30s\)/);
assert.match(qafqazinfoSource, /URL changed/);
assert.match(qafqazinfoSource, /DOM fully loaded/);
assert.match(qafqazinfoSource, /Search results detected/);
assert.match(qafqazinfoSource, /Results page ready/);
assert.match(qafqazinfoSource, /Current page processed/);
assert.match(qafqazinfoSource, /Pagination finished/);
assert.match(qafqazinfoSource, /ctx\.navigation\.click\(nextLink/);
assert.match(qafqazinfoSource, /window\.location\.assign\(nextUrl\)/);
assert.match(qafqazinfoSource, /Date\.now\(\) \+ 30000/);
assert.match(qafqazinfoSource, /intervalMs: 500/);
assert.match(qafqazinfoSource, /news:openArticleTab/);
assert.match(qafqazinfoSource, /\.panel-body\.news_text p, \.news_text p/);
assert.match(qafqazinfoSource, /\.news-time time, time\[datetime\]/);
assert.match(qafqazinfoSource, /\.panel-body > img\.img-responsive\[src\]/);
assert.match(qafqazinfoSource, /app\.parsers\.parseQafqazinfoDate/);
assert.doesNotMatch(qafqazinfoSource, /category:/);
assert.doesNotMatch(qafqazinfoSource, /views:/);
const backgroundSource = fs.readFileSync(path.join(root, 'background.js'), 'utf8');
const contentSource = fs.readFileSync(path.join(root, 'content.js'), 'utf8');
assert.match(backgroundSource, /news:openArticleTab/);
assert.match(backgroundSource, /chrome\.tabs\.create/);
assert.match(backgroundSource, /chrome\.tabs\.remove/);
assert.match(contentSource, /news:extractArticle/);
const facebookSource = fs.readFileSync(path.join(root, 'scrapers', 'facebook.js'), 'utf8');
const navigationSource = fs.readFileSync(path.join(root, 'core', 'navigation.js'), 'utf8');
assert.match(facebookSource, /parseFacebookDateFromHeaderHover/);
assert.match(facebookSource, /findAndHoverFacebookDateElement/);
assert.match(facebookSource, /findFacebookPostContainer/);
assert.match(facebookSource, /isCompleteFacebookPostContainer/);
assert.match(facebookSource, /Post rejected: missing author\/date after container retry/);
assert.match(facebookSource, /profile \? this\.allVisible\('a\[role="link"\]\[href\]'/);
assert.match(facebookSource, /Container candidate level=/);
assert.match(facebookSource, /resolveDateFromPermalink/);
assert.match(facebookSource, /postDate: app\.utils\.formatTimestamp\(postDate\)/);
assert.match(facebookSource, /Date candidates outside header ignored/);
assert.match(facebookSource, /Expand candidates found/);
assert.match(facebookSource, /attempt <= 5/);
assert.match(facebookSource, /expandFacebookFullText/);
assert.match(facebookSource, /extractFacebookAuthor/);
assert.match(facebookSource, /extractFacebookMedia/);
assert.match(facebookSource, /\[data-ad-rendering-role="profile_name"\]/);
assert.match(facebookSource, /Timestamp link found from header/);
assert.match(facebookSource, /\[data-ad-rendering-role="story_message"\]/);
assert.match(facebookSource, /focusFacebookSearchInput/);
assert.match(facebookSource, /typeFacebookSearchKeyword/);
assert.match(facebookSource, /pressFacebookSearchEnter/);
assert.match(facebookSource, /document\.activeElement === input/);
assert.match(facebookSource, /facebookUnsafeInteractionReason/);
assert.match(facebookSource, /\[data-ad-rendering-role="image"\]/);
assert.match(facebookSource, /a\[href\*="\/reel\/"\]/);
assert.match(facebookSource, /ambiguous-more-outside-message/);
assert.match(facebookSource, /settleFacebookInteraction/);
assert.match(facebookSource, /accidental content-info popup detected/);
assert.match(facebookSource, /'Escape', 'Escape', 27/);
assert.match(navigationSource, /options\.typeInput/);
assert.match(navigationSource, /options\.pressEnter/);
const tiktokSource = fs.readFileSync(path.join(root, 'scrapers', 'tiktok.js'), 'utf8');
const stateMachineSource = fs.readFileSync(path.join(root, 'core', 'state-machine.js'), 'utf8');
assert.match(tiktokSource, /switchToVideosTab/);
assert.match(tiktokSource, /Looking for Videos tab/);
assert.match(tiktokSource, /Videos tab confirmed/);
assert.match(tiktokSource, /for \(let attempt = 1; attempt <= 3; attempt\+\+\)/);
assert.doesNotMatch(tiktokSource, /location\.pathname\.includes\('\/search\/video'\) \|\| document\.querySelector\('a\[href\*="\/video\/"\]'\)/);
assert.match(tiktokSource, /openTikTokVideoAndScrape/);
assert.match(tiktokSource, /scraperProgress/);
assert.match(tiktokSource, /Caption selector matched/);
assert.match(tiktokSource, /text: caption\?\.text \|\| null/);
assert.doesNotMatch(tiktokSource, /parseCard\(/);
assert.match(tiktokSource, /openFirstVideoCard/);
assert.match(tiktokSource, /moveToNextViewerPost/);
assert.match(tiktokSource, /collectViewerMedia/);
assert.match(tiktokSource, /ArrowDown/);
assert.doesNotMatch(tiktokSource, /videoUrls/);
assert.doesNotMatch(tiktokSource, /assign\(target\.postUrl\)/);
assert.match(stateMachineSource, /if \(result\?\.navigating\)/);
assert.match(stateMachineSource, /scraperProgress: null/);
assert.match(stateMachineSource, /reason !== 'end-of-feed'/);
const serverSource = fs.readFileSync(path.join(root, 'core', 'server.js'), 'utf8');
const utilsSource = fs.readFileSync(path.join(root, 'core', 'utils.js'), 'utf8');
assert.doesNotMatch(serverSource, /optionalField|title|category/);
assert.doesNotMatch(utilsSource, /optionalField|title|category/);
assert.equal(globalThis.ScraperApp, undefined);

console.log('Static architecture checks passed');
